### ISSUE TITLE
pre-0.2.0 Roadmap

### ISSUE THREAD

**Issue by expiteRz** [expiteRz/koten.rz-public.xyz#1]
- [ ] Room overlay for OBS
- [ ] Save room information at that moment (This may be useful for reporting the illegal players)
- [ ] Support other regions (such as CTGPR Classic)

**Comment by expiteRz** [comment]
decided to add other regions support as an actual feature (former one is by just an accident)
